(()=>{_$$("pre").forEach(element=>{var div,parent=element.parentNode;parent.classList.contains("gutter")||((div=document.createElement("div")).className="code-area",parent.insertBefore(div,element),parent.removeChild(element),div.appendChild(element))});let expandThreshold=(window.REIMU_CONFIG?.code_block||{}).expand;if(_$$("figure.highlight").forEach(element=>{element.querySelector(".code-figcaption")||element.insertAdjacentHTML("afterbegin",`
  <div class="code-figcaption">
    <div class="code-left-wrap">
      <div class="code-decoration"></div>
      <div class="code-lang"></div>
    </div>
    <div class="code-right-wrap">
      <div class="code-copy icon-copy"></div>
      <div class="icon-chevron-down code-expand"></div>
    </div>
  </div>`),void 0!==expandThreshold&&(!1===expandThreshold||"number"==typeof expandThreshold&&element.querySelectorAll("td.code .line").length>expandThreshold)&&(element.classList.add("code-closed"),element.style.display="none",element.style.display="")}),_$$(".code-expand").forEach(element=>{element.off("click").on("click",()=>{element.closest("figure").classList.toggle("code-closed")})}),_$$("figure.highlight").forEach(element=>{var codeLanguage=element.className.split(" ")[1];if(codeLanguage){let langName=codeLanguage.replace("line-numbers","").trim().replace("language-","").trim();langName=langName.toUpperCase();codeLanguage=element.querySelector(".code-lang");codeLanguage&&(codeLanguage.innerText=langName)}}),window.ClipboardJS){let tips=window.REIMU_CONFIG?.clipboard_tips||{},clipboard=new ClipboardJS(".code-copy",{text:trigger=>{var selection=window.getSelection(),range=document.createRange();range.selectNodeContents(trigger.parentNode.parentNode.nextElementSibling.querySelector("td.code")),selection.removeAllRanges(),selection.addRange(range);let selectedText=selection.toString();return selectedText=tips.copyright?.enable&&selectedText.length>=tips.copyright?.count?selectedText+"\n\n"+(tips.copyright?.content??""):selectedText}});clipboard.on("success",e=>{e.trigger.classList.add("icon-check"),e.trigger.classList.remove("icon-copy");var successConfig=tips.success;let successText="Copy successfully (*^▽^*)";if("string"==typeof successConfig)successText=successConfig;else if("object"==typeof successConfig){let lang=document.documentElement.lang;var key=Object.keys(successConfig).find(key=>key.toLowerCase()===lang.toLowerCase());key&&successConfig[key]&&(successText=successConfig[key])}_$("#copy-tooltip").innerText=successText,_$("#copy-tooltip").style.opacity=1,setTimeout(()=>{_$("#copy-tooltip").style.opacity=0,e.trigger.classList.add("icon-copy"),e.trigger.classList.remove("icon-check")},1e3),e.clearSelection()}),clipboard.on("error",e=>{e.trigger.classList.add("icon-times"),e.trigger.classList.remove("icon-copy");var failConfig=tips.fail;let failText="Copy failed (ﾟ⊿ﾟ)ﾂ";if("string"==typeof failConfig)failText=failConfig;else if("object"==typeof failConfig){let lang=document.documentElement.lang;var key=Object.keys(failConfig).find(key=>key.toLowerCase()===lang.toLowerCase());key&&failConfig[key]&&(failText=failConfig[key])}_$("#copy-tooltip").innerText=failText,_$("#copy-tooltip").style.opacity=1,setTimeout(()=>{_$("#copy-tooltip").style.opacity=0,e.trigger.classList.add("icon-copy"),e.trigger.classList.remove("icon-times")},1e3)}),window.Pjax&&window.addEventListener("pjax:send",()=>{clipboard.destroy()},{once:!0}),window.AOS&&AOS.refresh()}})();